version: '3'
services:
    vault-server:
        image: vault
        container_name: vault
        command: ["server"]
        environment:
          - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/data"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": "1"}}'
          - VAULT_API_ADDR=http://0.0.0.0:8200
          - VAULT_PORT=8200
        volumes:
          - ./vault/data:/vault/data
        cap_add:
          - IPC_LOCK

    pyinstabot-downloader:
        build:
          context: .
          dockerfile: Dockerfile
          args:
            BOT_NAME: pyinstabot-downloader
        container_name: pyinstabot-downloader
        restart: always
        environment:
          - BOT_VAULT_APPROLE_ID=${VAULT_APPROLE_ID}
          - BOT_VAULT_APPROLE_SECRET_ID=${VAULT_APPROLE_SECRET_ID}
          - BOT_VAULT_ADDR=http://vault-server:8200
          - BOT_INSTA_RATE_LIMIT_TIMEOUT=15
          - BOT_INSTA_RATE_LIMIT_MAX_TIMEOUT=360
        depends_on:
          - vault-server
