# the main manifest for launching the release version of the project
---
version: '3'
services:
    pyinstabot-downloader:
        image: ghcr.io/obervinov/pyinstabot-downloader:v2.0.0
        container_name: pyinstabot-downloader
        restart: always
        environment:
            - PROJECT_ENVIRONMENT=dev
            - TELEGRAM_BOT_NAME=pyinstabot-downloader
            - VAULT_APPROLE_ID=${VAULT_APPROLE_ID}
            - VAULT_APPROLE_SECRETID=${VAULT_APPROLE_SECRETID}
            - VAULT_ADDR=${VAULT_ADDR}
            - LOGGER_LEVEL=INFO
            - MESSAGES_CONFIG=configs/messages.json
        volumes:
            - ../.config/instaloader:/home/python/.config/instaloader
