version: '3'
services:
    vault-server:
        image: vault
        container_name: vault
        command: ["server"]
        environment:
          - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/data"}}, "default_lease_ttl": "1h", "max_lease_ttl": "720h", "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": "1"}}'
          - VAULT_API_ADDR=http://0.0.0.0:8200
          - VAULT_PORT=8200
        volumes:
          - ./vault/data:/vault/data
        ports:
          - "0.0.0.0:8200:8200"
        cap_add:
          - IPC_LOCK

    pyinstabot-downloader:
        build:
          context: .
          dockerfile: Dockerfile
          args:
            PROJECT_NAME: pyinstabot-downloader
        container_name: pyinstabot-downloader
        restart: always
        environment:
          - BOT_NAME=pyinstabot-downloader
          - VAULT_APPROLE_ID=${VAULT_APPROLE_ID}
          - VAULT_APPROLE_SECRETID=${VAULT_APPROLE_SECRETID}
          - VAULT_ADDR=http://vault-server:8200
        depends_on:
          - vault-server
