name: Build release image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-release:
    uses: obervinov/_templates/.github/workflows/docker.yml@fixed-docker-login
