name: Create GitHub Release

on:
  push:
    branches: [main]

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.5
    needs: [pylint, verify-changelog]
