---
name: Create GitHub Release

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.5
