---
name: Test and Build release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
#  pylint:
#    uses: obervinov/_templates/.github/workflows/pylint.yaml@v1.0.11
#  verify-changelog:
#    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.0.11
  build-image:
    uses: obervinov/_templates/.github/workflows/docker.yaml@release/v1.0.12
    #needs: [pylint, verify-changelog]

