---
name: Test and Build release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

env:
  # yamllint disable-line rule:line-length
  PROJECT_DESCRIPTION: "This project is a telegram bot that allows you to create backups of content from your Instagram profile to Dropbox or Mega clouds, as well as in the local file system."


jobs:
#  pylint:
#    uses: obervinov/_templates/.github/workflows/pylint.yaml@v1.0.11
#  verify-changelog:
#    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.0.11
  build-image:
    uses: obervinov/_templates/.github/workflows/docker.yaml@v1.0.11
    #needs: [pylint, verify-changelog]
